### ISSUE TITLE
Catchable Fatal Error: Argument 2 passed to Mgilet\NotificationBundle\Manager\NotificationManager::addNotification() 

### ISSUE THREAD

**Issue by aimeric** [maximilienGilet/notification-bundle#2]
Hi,

I added an entity`email type array` in the table `Notification`. But when i'm trying to persist i get this error: 

>   Catchable Fatal Error: Argument 2 passed to Mgilet\NotificationBundle\Manager\NotificationManager::addNotification() must be an instance of Mgilet\NotificationBundle\Model\AbstractNotification, array given, called in C:\xampp\htdocs\Symfony\src\FLY\BookingsBundle\Controller\PostController.php on line 793 and defined

```
            $manager = $this->get('mgilet.notification');
            $notif = $manager->generateNotification('Test');
            //$notif->setMessage();
            //$notif->setLink();
            $commande = array();
            foreach ($entities as $entity) {
                $notif->setEmail($notif);
                $notif = $commande['entity'][$entity->getId()] = array(
                    $entity->getEmail());
            }
            $manager->addNotification($this->getUser(), $notif);
            $em->persist($notif);
            $em->flush();
```

if I delete this line :  `$manager->addNotification($this->getUser(), $notif);`

I will get the following error:

> EntityManager#persist() expects parameter 1 to be an entity object, array given.

How can i fix this error ?

Thank you

**Comment by maximilienGilet** [comment]
Hello, sorry for the delay.

There are two causes for your problem: 

First, the line 
`$notif = $commande['entity'][$entity->getId()] = array(
                    $entity->getEmail());`
seems suspicious.
It looks like you are affecting an array (`$commande['entity'][$entity->getId()]`) to the notification object.
Then, your $notif variable will be an array and not an AbstractNotification. So you won't be able to send the notification or persist it.

The intended way is by doing something like this:

```
    $manager = $this->get('mgilet.notification');
    $commande = array();
        foreach ($entities as $entity) {
            $notif = $manager->generateNotification('Test');
            $notif->setEmail($entity->getEmail());
            // i'm not sure what you do with this line so i'm setting the notification link with your entity's id
            $notif->setLink($entity->getId());
            $manager->addNotification($this->getUser(), $notif);
            $em->persist($notif);
        }
    $em->flush();
```

That leads to the second problem : 

Currently, if you notify multiple users for the same thing, you will need to create as many notification objects as users. Which is for me a problem, because it's heavy and not intuitive.

The solution of this problem will be the main feature of the v2 i'm thinking about.

So thank you for using my bundle and stay tuned for the v2 :yum:

**Comment by maximilienGilet** [comment]
I know it's been a while, but version 2.0 just got released. It features the ability to add a notification to many user entities, so your issue is now fixed
