### ISSUE TITLE
How to define entity in Twig?

### ISSUE THREAD

**Issue by mrvnklm** [maximilienGilet/notification-bundle#32]
Hey, just tried out your bundle with symfony flex and facing some issues. How to define notifiableEntity in twig template using  mgilet_notification_render()? Just want to see user notifications, but can't pass the entity.

**Comment by maximilienGilet** [comment]
Hi @mrvnklm !

You can simply pass the `app.user` to the `mgilet_notification_render()` twig method.

It should look like `{{  mgilet_notification_render(app.user) }}`

**Comment by mrvnklm** [comment]
Oh okay thank you, didn't know entity classes are available like that in twig. Working now. I have three more questions:
1. Is there a way to notify all users at once without creating an array with all users inside?
2. The notification dropdown widget on the readme page, is that available as well? Looks like its some kind of AdminLTE implementation?
3. Is it possible to implement the manager as dependency injection? Cant find a Manager Interface

**Comment by maximilienGilet** [comment]
1. In order to notify all users, the simplest way is to create a notification and adding it to all users : 
```php
$manager = $this->get('mgilet.notification');
$notif = $manager->createNotification('test', 'test message');
$manager->addNotification(/* fetch all user here */, $notif, true /* optional true argument to directly flush */);
```

2. The template was available in the first version of the bundle. It was removed because it was Bootstrap specific. It was simply a Bootstrap dropdown with notifications inside (with buttons for actions such as "mark as seen")

3. The manager is called `mgilet.notification`. Example of custom manager using the NotificationManager : 

```yaml
    App\Manager\CustomManager:
        arguments: [ '@mgilet.notification' ]
```
