### ISSUE TITLE
rendered notifications list contains no html

### ISSUE THREAD

**Issue by henrikj242** [maximilienGilet/notification-bundle#63]
Hi, I've added this to my nav header:  `{{ mgilet_notification_render(app.user) }}`, but there is no html in the rendered string. Not even if I use the twig `raw` filter.

So after adding the demo notification a couple of time, the rendered list looks like this:

    <nav class="collapse navbar-collapse" role="navigation">
        <p>Notifications :
            Hello world! - This a notification.
            Hello world! - This a notification.
        </p>
    ...
What could cause this, and how could it be fixed?

**Comment by henrikj242** [comment]
I fixed the missing html just by providing the template like this:
```
{{ mgilet_notification_render(app.user, { 'template': '@MgiletNotificationBundle/Resources/views/notifications.html.twig' }) }}
```

But the now html looks noting like the screenshot / gif in the repo's README. 

Is there an easy way to just make it look like that, or do we have to implement all the styling etc ourselves? 
@maximilienGilet ?

**Comment by maximilienGilet** [comment]
Hi @henrikj242, thanks for using the bundle.

This template was available in the first version of the bundle, you can find it [here](https://github.com/maximilienGilet/notification-bundle/blob/8cc4e964c0cfcad8567146200999b8ceb5821985/Resources/views/notification_dropdown.html.twig)

It was removed because it depends on bootstrap and jquery.

I don't think this works with the current implementation, feel free to edit this. If it works for you please submit a pull request in a new documentation entry such as "examples"
